---
- hosts: nginx_dev
  tasks:
   - name: Configure vhost1
     copy: src=/home/cristian/BCE/ansible/vhosts/vhost1.conf dest=/etc/nginx/conf.d/vhost1.conf owner=root group=root mode=0644
   - name: Configure vhost2
     copy: src=/home/cristian/BCE/ansible/vhosts/vhost2.conf dest=/etc/nginx/conf.d/vhost2.conf owner=root group=root mode=0644
     notify:
      - Start Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=reloaded
